// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6YkZkx-pp_DCl_2-n-IGY8CsjFFo_-Kw',
    appId: '1:627544527168:web:8628613c76fda1e53e6aa5',
    messagingSenderId: '627544527168',
    projectId: 'campanha-dbf2b',
    authDomain: 'campanha-dbf2b.firebaseapp.com',
    databaseURL: 'https://campanha-dbf2b-default-rtdb.firebaseio.com',
    storageBucket: 'campanha-dbf2b.appspot.com',
    measurementId: 'G-5HKZ0XSZ4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOPYrnzebHgf8Iryz0QBDR_dcl_eo_UzA',
    appId: '1:627544527168:android:f053da37ae15a93a3e6aa5',
    messagingSenderId: '627544527168',
    projectId: 'campanha-dbf2b',
    databaseURL: 'https://campanha-dbf2b-default-rtdb.firebaseio.com',
    storageBucket: 'campanha-dbf2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSnjKGtrxm5vUhPZ1_1AwpwQMFyqmKfFo',
    appId: '1:627544527168:ios:41bbabf5f01bdcdb3e6aa5',
    messagingSenderId: '627544527168',
    projectId: 'campanha-dbf2b',
    databaseURL: 'https://campanha-dbf2b-default-rtdb.firebaseio.com',
    storageBucket: 'campanha-dbf2b.appspot.com',
    iosBundleId: 'com.example.campanha.campanha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSnjKGtrxm5vUhPZ1_1AwpwQMFyqmKfFo',
    appId: '1:627544527168:ios:41bbabf5f01bdcdb3e6aa5',
    messagingSenderId: '627544527168',
    projectId: 'campanha-dbf2b',
    databaseURL: 'https://campanha-dbf2b-default-rtdb.firebaseio.com',
    storageBucket: 'campanha-dbf2b.appspot.com',
    iosBundleId: 'com.example.campanha.campanha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6YkZkx-pp_DCl_2-n-IGY8CsjFFo_-Kw',
    appId: '1:627544527168:web:5318af11e672ea643e6aa5',
    messagingSenderId: '627544527168',
    projectId: 'campanha-dbf2b',
    authDomain: 'campanha-dbf2b.firebaseapp.com',
    databaseURL: 'https://campanha-dbf2b-default-rtdb.firebaseio.com',
    storageBucket: 'campanha-dbf2b.appspot.com',
    measurementId: 'G-7QH3Q5WVVV',
  );
}
